name: 03-workflow-runners
on: push
jobs:
  echo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Echo on Ubuntu
        run: |
            echo "This is running on Ubuntu"
            echo "Runner OS: $RUNNER_OS"
