name: 04-using-actions
on: push

jobs:
    build:
        runs-on: unbuntu-latest
        steps:
        - name: Checkout our code
          uses: actions/checkout@v4
        - name: Printing folders
          run: ls -la

        # 0. Checkout our code
        # 1. Install deps of our react application
        # 2. Execute automated tests

