name: 05-2-filter-activity-types
on: 
    pull_request:
        types: [closed]
jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - name: Show the trigger event
              run: echo "This workflow was triggered by a ${{ github.event_name }} event of type ${{ github.event.action }}."