name: 06-context
on: 
    push:
    workflow_dispatch:
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Show GitHub Context
              run: |
                echo "This workflow was triggered by a ${{ github.event_name }} event."
                echo "Repository: ${{ github.repository }}"
                echo "Actor: ${{ github.actor }}"
                echo "SHA: ${{ github.sha }}"
                echo "Ref: ${{ github.ref }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Job: ${{ github.job }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "Event Details: ${{ toJson(github.event) }}"
                echo "Workspace: ${{ github.workspace }}"
                echo "workflow: ${{ github.workflow }}"
                echo "Actor: ${{ github.actor }}"
            
            - name: Retrieve Variable
              run: |
                echo "The value of MY_VAR is: ${{ env.MY_VAR }}"
 
     