name: 06-context
run-name: 06 - context | ${{ inputs.debug }}
on: 
    # push:
    workflow_dispatch:
        inputs:
           debug:
                description: 'Enable debug mode'
                type: boolean
                default: false
env:
    MY_WORKFLOW_VAR: 'Workflow'
    MY_OVERWRITTEN_VAR: 'workflow'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: 'Job'
            MY_OVERWRITTEN_VAR: 'job'
        steps:
            - name: Show GitHub Context
              run: |
                echo "This workflow was triggered by a ${{ github.event_name }} event."
                echo "Repository: ${{ github.repository }}"
                echo "Actor: ${{ github.actor }}"
                echo "SHA: ${{ github.sha }}"
                echo "Ref: ${{ github.ref }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Job: ${{ github.job }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "Event Details: ${{ toJson(github.event) }}"
                echo "Workspace: ${{ github.workspace }}"
                echo "workflow: ${{ github.workflow }}"
                echo "Actor: ${{ github.actor }}"
            
            - name: Retrieve Variable
              run: |
                echo "The value of MY_VAR is:. ${{ vars.MY_VAR }}"
            - name: Print env variables -1
              env:
                MY_STEP_VAR: 'Step'
                MY_OVERWRITTEN_VAR: 'step'
              run: |
                echo "The value of MY_WORKFLOW_VAR is: ${{ env.MY_WORKFLOW_VAR }}"
                echo "The value of MY_OVERWRITTEN_VAR is: ${{ env.MY_OVERWRITTEN_VAR }}"

            - name: Print env variables -2
              run: |
                 echo "The value of MY_WORKFLOW_VAR is: ${{ env.MY_WORKFLOW_VAR }}"
                 echo "The value of MY_OVERWRITTEN_VAR is: ${{ env.MY_OVERWRITTEN_VAR }}"

