name: 09-using-functions
on:
    # pull_request:
    workflow_dispatch:
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:

            - name: Print PR title
              run: |
                echo "The title of this PR is: ${{ github.event.pull_request.title }}"
            - name: Print PR label
              run: |  
               cat << EOF
               ${{ toJSON(github.event.pull_request.labels) || 'No labels found' }}    
               EOF
            - name: Bug Step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
              run: |
                echo "This PR is related to a bug."

            # - name: Sleep for 20 seconds
            #   run: sleep 20
            
            # - name: Failing Step
            #   run: |
            #     echo "This step will fail"
            #     exit 1
            - name: This step will be skipped
              if: ${{ success() }}
              run: echo "I will pring if the previous step succeed"

            - name: This step will run even if the previous step failed
              if: ${{ failure() }}
              run: echo "I will pring if the previous step failed"

            - name: I will execute if not cancelled
              if: ${{ !cancelled() }}
              run: echo "I will execute even if the workflow was cancelled"
            
            - name: I will execute when the workflow is cancelled   
              if: ${{ cancelled() }}
              run: echo "I will execute only if the workflow was cancelled"

            


