name: 10 - Controlling the execution flow
on: 
    workflow_dispatch:
        inputs:
           pass-unit-tests:
                description: 'Pass unit tests'
                type: boolean
                default: true
jobs:
    lint-built:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and Build
              run: |
                echo "Linting the code..."
                echo "Building the project..."
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Running unit tests
              run : echo "Running unit tests..."
            - name: Failing tests
              if: ${{ !inputs.pass-unit-tests }}
              run: exit 1
    deploy-non-prod:
        runs-on: ubuntu-latest
        needs: 
            - lint-built
            - unit-tests
        steps:
            - name: Deploy to non-prod
              run: echo "Deploying to non-production environment..."
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-non-prod
        steps:
            - name: Running end-to-end tests
              run: echo "Running end-to-end tests..."
    load-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-non-prod
        steps:
            - name: Running load tests
              run: echo "Running load tests..."
    deploy-prod:
        runs-on: ubuntu-latest
        needs: 
            - e2e-tests
            - load-tests
        steps:
            - name: Deploy to production
              run: echo "Deploying to production environment..."
